### PR TITLE
Update cs2.json

### PR DESCRIPTION
**Pull request by stefanx111**
Changed appid in installation script

### CODE REVIEW

**Review by 1zc — APPROVED** [review]
Thank you, haven't slept at all lol

**Comment by 1zc** [comment]
Although, problem here is we can't install 730 without Steam user and pass set up - I'll investigate this later

**Comment by stefanx111** [comment]
I put an account(removed steam guard) with cs2 in the variables (SRCDS_LOGIN, SRCDS_LOGIN_PASS) and it works.
This is the only way for now until dedicated server support comes out. This is from today(https://steamcommunity.com/faqs/steam-help/view/5ED2-ED8E-81F4-0C18#commserver)

**Comment by 1zc** [comment]
I figured it out, will merge this and commit another fix for the install login

**Pull request merged**
